In [ ]:
import pandas as pd
df = pd.read_csv("Mall_Customers.csv")

In [ ]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [ ]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df.to_csv("cleaned_data.csv", index=False)